
name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
    
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1
      with:
        node-version: "14.x"
        cache: "yarn"
    
    - name: Install Dependencies
      run: yarn install
        
    - name: Generate Build
      run: yarn build
    
    - name: Deploy to Github Pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        build_dir: ./build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}